name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:        # Allows you to trigger it manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping Render
        run: curl -s https://similarity-0dbg.onrender.com/ping
